<?php

namespace ShoppingFeed\ShoppingFeedWC\Feed;

use ShoppingFeed\ShoppingFeedWC\ShoppingFeed;
use ShoppingFeed\ShoppingFeedWC\ShoppingFeedHelper;

class AsyncGenerator extends Generator {

	/**
	 * Launch the feed generation process
	 */
	public function launch() {
		// Ensure all necessary directories have been created.
		ShoppingFeed::add_sf_directory();

		// Clean directory containing feed parts generated by the async generator.
		// This is to avoid reusing old parts that could remain if a previous execution of the generator failed.
		$this->clean_feed_parts_directory();

		$part_size = ShoppingFeedHelper::get_sf_part_size();
		ShoppingFeedHelper::get_feedbuilder_manager()->launch_feed_generation( $part_size );
	}

	/**
	 * Remove all XML files in the feed parts directory.
	 *
	 * @return void
	 */
	public function clean_feed_parts_directory() {
		$dir_parts = ShoppingFeedHelper::get_feed_parts_directory();
		$files     = glob( $dir_parts . '/' . '*.xml' ); // @codingStandardsIgnoreLine.
		if ( is_array( $files ) && ! empty( $files ) ) {
			foreach ( $files as $file ) {
				wp_delete_file( $file );
			}
		}
	}
}
