name: Quality

on:
  pull_request:
  push:
    branches:
      - master

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ 7.4' ]
    name: PHP ${{ matrix.php-versions }} Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl #optional, setup extensions

      - name: Check composer
        run: composer validate

      - name: Add dependencies
        run: composer install

      - name: Check cs
        run: composer cs

      - name: Check psalm
        run: composer psalm